const competitions = [
    {
        "id": "1",
        "name": "SEAMO (Southeast Asian Mathematical Olympiad) ",
        "location": "Singapore",
        "method": "Offline",
        "language": "English",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "19 October 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Paper K: Kindergarten\nPaper A: Grade 1 & 2\nPaper B: Grade 3 & 4\nPaper C: Grade 5 & 6\nPaper D: Grade 7 & 8\nPaper E: Grade 9 & 10\nPaper F: Grade 11 & 12\n",
        "organizedBy": "Terry Chew Academy",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Paper K (45 minutes):\n15 Multiple Choice\n\nPaper A - F (90 minutes):\n- Section A: 10 Multiple Choice (3 marks each)\n- Section B: 10 Multiple Choice (4 marks each)\n- Section C: 5 Short Answer (6 marks each)",
        "awards": "For each grade level, awards will be given based on country rank:\n\nTop 8%: Gold Medal\nNext 12%: Silver Medal\nNext 20%: Bronze Medal",
        "finalRoundInfo": "Top 40% are eligible to join Champions Division of SEAMO X. The Next 60% can still join SEAMO X Open Division\nSEAMO X 2025 will be held on 17-20 Jan 2025 in Kuala Lumpur, Malaysia",
        "compFee": "",
        "website": "https://seamo-official.org",
        "samplePaper": "https://seamo-official.org/resources",
        "logo":"seamo.png"
    },
    {
        "id": "2",
        "name": "WMI (World Mathematics Invitational)",
        "location": "Taiwan",
        "method": "Offline",
        "language": "English",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "23 March 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11, G12",
        "organizedBy": "WMI Organizing Committee",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Section A: Logical Reasoning\n- 10 Multiple Choice (4 marks each)\n- 5 Multiple Choice (6 marks each)\n\nSection B: Applications\n10 Multiple Choice (10 marks each)",
        "awards": "For each grade level, awards will be given based on country rank:\n\nTop 10%: Gold Medal\nNext 10%: Silver Medal\nNext 10%: Bronze Medal",
        "finalRoundInfo": "Only Gold is eligible for the Final Round on 12-16 July 2024 in Kuala Lumpur, Malaysia",
        "compFee": "",
        "website": "https://www.wminv.org/",
        "samplePaper": "bit.ly/wmipast",
        "logo":"wmi.jpeg"
    },
    {
        "id": "3",
        "name": "SASMO (Singapore and Asian Schools Math Olympiad)",
        "location": "Singapore",
        "method": "Online & Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Grade 1 - Grade 12",
        "date": "23 March 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "G1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11, G12",
        "organizedBy": "SIMCC (Singapore International Math Contests Center)",
        "indonesiaLocalOrganizer": "SIMCC Indonesia",
        "structure": "Section A: 15 Multiple Choice\n- 2 marks for each correct answer\n- 0 mark for each unanswered question\n- 1 mark deducted for each wrong answer\n\nSection B: 10 Short Answer\n- 4 marks for each correct answer\n- No penalty for wrong answer\n\nTo avoid negative scores, each student will begin with 15 marks.\nTotal Score: 85 marks (90 minutes)",
        "awards": "For each grade level, awards will be given based on global rank:\n\nPerfect Score\nTop 8%: Gold Medal\nNext 12%: Silver Medal\nNext 20%: Bronze Medal\nNext 10%: Honorable Mention",
        "finalRoundInfo": "Bronze & Above is eligible to join SMGF (Singapore Math Global Finals) and SIMOC (SIngapore International Math Olympiad Challenge)\n\nSilver & Above is eligible to join IJMO (International Junior Math Olympiad)\n",
        "compFee": "",
        "website": "https://sasmo.sg/",
        "samplePaper": "",
        "logo":"sasmo.png"
    },
    {
        "id": "4",
        "name": "AMO (American Mathematics Olympiad)",
        "location": "Singapore",
        "method": "Online & Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "Yes",
        "grades": "Grade 2 - Grade 12",
        "date": "G7-G12: 26 October 2024\nG2-G6: 2 November 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11, G12",
        "organizedBy": "SIMCC (Singapore International Math Contests Center)",
        "indonesiaLocalOrganizer": "SIMCC Indonesia",
        "structure": "Section A: 15 Multiple Choice (3 marks each)\nSection B: 5 Multiple Choice (5 marks each)\nSection C: 5 Short Answer (6 marks each)\n\nNo penalty for wrong answer\nTotal Score: 100 marks (90 minutes)",
        "awards": "For each grade level, awards will be given based on global rank:\n\nPerfect Score\nTop 8%: Gold Medal\nNext 12%: Silver Medal\nNext 20%: Bronze Medal\nNext 10%: Honorable Mention",
        "finalRoundInfo": "Bronze & Above is eligible to join SMGF (Singapore Math Global Finals) and SIMOC (SIngapore International Math Olympiad Challenge)\n\nSilver & Above is eligible to join IJMO (International Junior Math Olympiad)\n",
        "compFee": "IDR 450,000",
        "website": "https://amo.sg/",
        "samplePaper": "",
        "logo":"AMO.jpg"
    },
    {
        "id": "5",
        "name": "SMC (Singapore Math Challenge)",
        "location": "Singapore",
        "method": "Online & Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "31 August 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11, G12",
        "organizedBy": "SIMCC (Singapore International Math Contests Center)",
        "indonesiaLocalOrganizer": "SIMCC Indonesia",
        "structure": "Section A: 15 Multiple Choice (2 marks each)\nSection B: 10 Short Answer (4 marks each)\nSection C: 6 Short Answer (5 marks each)\n\nNo penalty for wrong answer\nTotal Score: 100 marks (90 minutes)",
        "awards": "For each grade level, awards will be given based on global rank:\n\nPerfect Score\nTop 8%: Gold Medal\nNext 12%: Silver Medal\nNext 20%: Bronze Medal\nNext 10%: Honorable Mention",
        "finalRoundInfo": "Bronze & Above is eligible to join SMGF (Singapore Math Global Finals)",
        "compFee": "",
        "website": "https://singamath.com/",
        "samplePaper": "",
        "logo":"SMC.png"
    },
    {
        "id": "6",
        "name": "SMGF (Singapore Math Global Finals)",
        "location": "Singapore",
        "method": "Online",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Grade 1 - Grade 12",
        "date": "3 March 2024",
        "curated": "Yes",
        "prerequisites": "Bronze & Above from SASMO / AMO / SMC",
        "category": "G1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11, G12",
        "organizedBy": "SIMCC (Singapore International Math Contests Center)",
        "indonesiaLocalOrganizer": "SIMCC Indonesia",
        "structure": "Section A: 15 Multiple Choice (2 marks each)\nSection B: 10 Short Answer (4 marks each)\nSection C: 6 Short Answer (5 marks each)\n\nNo penalty for wrong answer\nTotal Score: 100 marks (90 minutes)",
        "awards": "For each grade level, awards will be given based on global rank:\n\nPerfect Score\nTop 10%: Gold Medal\nNext 15%: Silver Medal\nNext 25%: Bronze Medal\nNext 20%: Honorable Mention",
        "finalRoundInfo": "Silver & Above is eligible to join SIMOC (SIngapore International Math Olympiad Challenge) and IJMO (International Junior Math Olympiad)\n",
        "compFee": "",
        "website": "https://singamath.com/",
        "samplePaper": ""
    },
    {
        "id": "7",
        "name": "SIMOC (Singapore International Math Olympiad Challenge)",
        "location": "Singapore",
        "method": "Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Grade 1 - Grade 12",
        "date": "20 - 23 July 2024, Singapore",
        "curated": "Yes",
        "prerequisites": "Bronze & Above from SASMO / AMO\nSilver & Above from SMGF",
        "category": "G1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11, G12",
        "organizedBy": "SIMCC (Singapore International Math Contests Center)",
        "indonesiaLocalOrganizer": "SIMCC Indonesia",
        "structure": "Math Olympiad Contest (Individual):\nSection A: 15 Multiple Choice\n- 2 marks for each correct answer\n- 0 mark for each unanswered question\n- 1 mark deducted for each wrong answer\n\nSection B: 10 Short Answer\n- 4 marks for each correct answer\n- No penalty for wrong answer\n\nTo avoid negative scores, each student will begin with 15 marks.\nTotal Score: 85 marks (90 minutes)\n\nMind Sports Challenge (Team-Based)\n\nMaths Warriors and Maths Master Mind Challenge (Team-Based)",
        "awards": "Math Olympiad Contest (Individual):\nFor each grade level, awards will be given based on global rank:\nPerfect Score\nTop 10%: Gold Medal\nNext 15%: Silver Medal\nNext 25%: Bronze Medal\nNext 20%: Honorable Mention\n\nMind Sports Challenge / Maths Warriors and Maths Master Mind Challenge (Team-Based)\nAwards for each division:\nTop 8%: Gold Medal\nNext 12%: Silver Medal\nNext 20%: Bronze Medal\n",
        "finalRoundInfo": "Bronze & Above is eligible to join IJMO (International Junior Math Olympiad)",
        "compFee": "",
        "website": "https://simoc.sg/",
        "samplePaper": ""
    },
    {
        "id": "8",
        "name": "IJMO (International Junior Math Olympiad)",
        "location": "Singapore",
        "method": "Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "Yes",
        "grades": "Grade 1 - Grade 12",
        "date": "6 - 10 December 2024, Turkey",
        "curated": "Yes",
        "prerequisites": "Silver & Above from SASMO / AMO / SMGF\nBronze & Above from SIMOC",
        "category": "G1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11, G12",
        "organizedBy": "SIMCC (Singapore International Math Contests Center)",
        "indonesiaLocalOrganizer": "SIMCC Indonesia",
        "structure": "Section A: 10 Multiple Choice\n- 2 marks for each correct answer\n- 0 mark for each unanswered question\n- 1 mark deducted for each wrong answer\n\nSection B: 10 Multiple Choice\n- 3 marks for each correct answer\n- 0 mark for each unanswered question\n- 1 mark deducted for each wrong answer\n\nSection C: 10 Short Answer\n- 5 marks for each correct answer\n- No penalty for wrong answer\n\nTo avoid negative scores, each student will begin with 20 marks.\nTotal Score: 120 marks (90 minutes)\"",
        "awards": "For each grade level, awards will be given based on global rank:\n\nPerfect Score\nTop 10%: Gold Medal\nNext 15%: Silver Medal\nNext 25%: Bronze Medal\nNext 20%: Honorable Mention\"",
        "finalRoundInfo": "",
        "compFee": "",
        "website": "https://ijmo.asia/",
        "samplePaper": ""
    },
    {
        "id": "9",
        "name": "AIMO (Asia International Mathematical Olympiad)",
        "location": "Hong Kong",
        "method": "Offline",
        "language": "English",
        "showRegister": "No",
        "grades": "Grade 2 - Grade 12",
        "date": "4 May 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "G2, G3, G4, G5, G6,\nG7, G8, G9, \nSenior Secondary (G10-G12)",
        "organizedBy": "AIMO Union",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Section A: 8 Short Answer (4 marks each)\nSection B: 8 Short Answer (5 marks each)\nSection C: 4 Short Answer (7 marks each)\n\nTotal Score: 100 marks (90 minutes)",
        "awards": "For each grade level, awards will be given based on country rank:\n\nTop 10%: Gold Medal\nNext 20%: Silver Medal\nNext 30%: Bronze Medal",
        "finalRoundInfo": "Only Gold is eligible for the Final Round on 27-31 July 2024 in Seoul & Incheon, South Korea",
        "compFee": "",
        "website": "https://aimo.world/",
        "samplePaper": "bit.ly/aimosample2"
    },
    {
        "id": "10",
        "name": "GMEC (Global Mathematics Elite Competition)",
        "location": "Hong Kong",
        "method": "Offline",
        "language": "English",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "11 May 2024",
        "curated": "No",
        "prerequisites": "None",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nG10, G11\n\n2 Different papers for each grade:\n- Paper A (Mathematics)\n- Paper B (Mathematical Olympiad)\n\n",
        "organizedBy": "First Education Group",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Paper A (Mathematics):\n20 Short Answer (10 marks each)\n\nPaper B (Mathematical Olympiad):\n20 Short Answer (10 marks each)\n\nTotal Duration: 120 minutes",
        "awards": "For each grade level, awards will be given based on country rank.\n\nFor each paper:\n\nTop 10%: Gold Medal\nNext 15%: Silver Medal\nNext 25%: Bronze Medal",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round on 16-20 August 2024 in Hong Kong",
        "compFee": "",
        "website": "",
        "samplePaper": ""
    },
    {
        "id": "11",
        "name": "HXC (Hua Xia Cup) China Mathematical Olympiad",
        "location": "Hong Kong",
        "method": "Online",
        "language": "English",
        "showRegister": "No",
        "grades": "Grade 1 - Grade 9",
        "date": "6 April 2024",
        "curated": "No",
        "prerequisites": "None",
        "category": "G1, G2, G3, G4, G5, G6,\nG7, G8, G9",
        "organizedBy": "Hong Kong & China Mathematical Olympiad Association",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Part A: 10 Short Answer (5 marks each)\nPart B: 10 Short Answer (7 marks each)\n\nTotal Score: 120 marks\nDuration: 60 minutes (G1-G6) / 75 minutes (G7-G9)",
        "awards": "For each grade level, awards will be given based on global rank:\n\nTop 10%: Gold Medal\nNext 20%: Silver Medal\nNext 30%: Bronze Medal",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round on 18 May 2024 online",
        "compFee": "",
        "website": "",
        "samplePaper": "bit.ly/hxcpastpapers"
    },
    {
        "id": "12",
        "name": "FMO (Fermat Mathematical Olympiad)",
        "location": "Vietnam",
        "method": "Online",
        "language": "English",
        "showRegister": "Yes",
        "grades": "Grade 1 - Grade 12",
        "date": "2 November 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "G1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nSenior Secondary (G10-G12)",
        "organizedBy": "Fermat Education",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Section A: 10 Multiple Choice (3 marks each)\nSection B: 5 Multiple Choice (5 marks each)\nSection C: 5 Multiple Choice (7 marks each)\nNo penalty for wrong answer\n\nSection D: 1 Short Answer (10 marks)\n10 marks deducted for wrong answer\n\nDuration: 75 minutes (G1-G6) / 90 minutes (G7-G12)",
        "awards": "Top 10%: Gold Medal\nNext 20%: Silver Medal\nNext 30%: Bronze Medal\nNext 20%: Merit Certificate",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round on 10-12 January 2025 in Da Nang, Vietnam",
        "compFee": "IDR 280,000",
        "website": "",
        "samplePaper": "bit.ly/fmosamplepapers"
    },
    {
        "id": "13",
        "name": "ISMC (International Singapore Mathematics Competition)",
        "location": "Singapore",
        "method": "Online",
        "language": "English",
        "showRegister": "No",
        "grades": "Grade 2 - Grade 6",
        "date": "25 May 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "G2, G3, G4, G5, G6",
        "organizedBy": "Marshall Cavendish Education",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Section A: Multiple Choice\nQ1-Q5: 2 marks each\nQ6-Q10: 3 marks each\n\nSection B: Short Answer\nQ11-Q20: 4 marks each\n\nSection C: Problem Solving\nQ21-Q25: 4 marks each\nQ26-Q28: 5 marks each \n\nDuration: 90 minutes",
        "awards": "Gold / Silver / Bronze",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round in June 2024 in Singapore",
        "compFee": "",
        "website": "",
        "samplePaper": "bit.ly/ismcpapers"
    },
    {
        "id": "14",
        "name": "Mathlympics",
        "location": "Singapore",
        "method": "Online",
        "language": "English",
        "showRegister": "No",
        "grades": "Grade 4 - Grade 7",
        "date": "25 May 2024",
        "curated": "No",
        "prerequisites": "None",
        "category": "Open Category (Same paper for G4-G7)",
        "organizedBy": "Marshall Cavendish Education",
        "indonesiaLocalOrganizer": "Edukultur",
        "structure": "Vault Section: First 90 minutes\nQ1-Q10: 2 marks each (1-2 bonus marks will be given for 9-10 correct answers respectively)\nQ11-Q20: 4 marks each (3-5 bonus marks will be given for 8-10 correct answers respectively)\nQ21-Q28: 5 marks each (5-7 bonus marks will be given for 6-8 correct answers respectively)\n\nSprint Section: Last 30 minutes\nQ1-Q30: 1 mark each",
        "awards": "Gold / Silver / Bronze",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round in June 2024 in Singapore",
        "compFee": "",
        "website": "",
        "samplePaper": ""
    },
    {
        "id": "15",
        "name": "TIMO (Thailand International Mathematical Olympiad)",
        "location": "Thailand",
        "method": "Online & Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "14 September 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nSenior Secondary (G10-G12)",
        "organizedBy": "OCEC (Olympiad Champion Education Center)",
        "indonesiaLocalOrganizer": "PPM",
        "structure": "25 Short Answer (4 marks each) in 90 minutes:\n- Logical Thinking: 5 Questions\n- Arithmetic / Algebra: 5 Questions\n- Number Theory: 5 Questions\n- Geometry: 5 Questions\n- Combinatorics: 5 Questions\n\nTotal Score: 100 marks",
        "awards": "Score 80 and above: Gold Medal\nScore 60 - <80: Silver Medal\nScore 40 - <60: Bronze Medal\nScore 20 - <40: Merit Certificate",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round on 22 February 2025 in Chiang Mai, Thailand or online",
        "compFee": "",
        "website": "http://www.thaiimo.com/",
        "samplePaper": ""
    },
    {
        "id": "16",
        "name": "BBB (Big Bay Bei) Hongkong-Macao Greater Bay Area Mathematical Olympiad ",
        "location": "Hong Kong",
        "method": "Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "Yes",
        "grades": "Kindergarten - Grade 12",
        "date": "2 November 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nSenior Secondary (G10-G12)",
        "organizedBy": "OCEC (Olympiad Champion Education Center)",
        "indonesiaLocalOrganizer": "PPM",
        "structure": "Section A: 10 Short Answer (4 marks each)\nSection B: 10 Short Answer (5 marks each)\nSection C: 5 Short Answer (7 marks each)\n\nTotal Score: 125 marks (75 minutes)",
        "awards": "Top 8%: Gold Medal\nNext 16%: Silver Medal\nNext 24%: Bronze Medal\nScore Above Standard: Merit Certificate",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round on 15 March 2025 in Hong Kong or online",
        "compFee": "IDR 325,000",
        "website": "https://www.bigbaybei.org/",
        "samplePaper": ""
    },
    {
        "id": "17",
        "name": "HKIMO (Hong Kong International Mathematical Olympiad)",
        "location": "Hong Kong",
        "method": "Online & Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "30 March 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nSenior Secondary (G10-G12)",
        "organizedBy": "OCEC (Olympiad Champion Education Center)",
        "indonesiaLocalOrganizer": "PPM",
        "structure": "25 Short Answer (4 marks each) in 90 minutes:\n- Logical Thinking: 5 Questions\n- Arithmetic / Algebra: 5 Questions\n- Number Theory: 5 Questions\n- Geometry: 5 Questions\n- Combinatorics: 5 Questions\n\nTotal Score: 100 marks",
        "awards": "Score 80 and above: Gold Medal\nScore 60 - <80: Silver Medal\nScore 40 - <60: Bronze Medal\nScore 20 - <40: Merit Certificate",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round on 24 August 2024 in Hong Kong, or online",
        "compFee": "",
        "website": "http://www.hongkongimo.com/",
        "samplePaper": ""
    },
    {
        "id": "18",
        "name": "PhIMO (Philippines International Mathematical Olympiad)",
        "location": "Philippines",
        "method": "Online & Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "26 May 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nJunior Secondary (G10), \nSenior Secondary (G11-G12)",
        "organizedBy": "Math Olympiads Training League Inc (MOTLI)",
        "indonesiaLocalOrganizer": "PPM",
        "structure": "Q1-Q10: Multiple Choice (2 marks each)\nQ11-Q20: Short Answer (3 marks each)\nQ21-Q25: Short Answer (5 marks each)\n\nTotal Score: 75 marks (90 minutes)",
        "awards": "Score 80% and above: Gold Medal\nScore 65% - <80%: Silver Medal\nScore 50% - <65%: Bronze Medal\nScore 40% - <50%: Merit Certificate",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round on 21 September 2024 in Manila, Philippines, or online",
        "compFee": "",
        "website": "",
        "samplePaper": ""
    },
    {
        "id": "19",
        "name": "WIMO (World International Mathematical Olympiad)",
        "location": "Hong Kong",
        "method": "Offline",
        "language": "English",
        "showRegister": "No",
        "grades": "Kindergarten - Grade 12",
        "date": "4-5 January 2025",
        "curated": "Yes",
        "prerequisites": "2 Golds from TIMO Final / BBB Final / HKIMO Final",
        "category": "KG,\nG1, G2, G3, G4, G5, G6,\nG7, G8, G9, \nSenior Secondary (G10-G12)",
        "organizedBy": "OCEC (Olympiad Champion Education Center)",
        "indonesiaLocalOrganizer": "PPM",
        "structure": "30 Short Answer (6 marks each) in 120 minutes:\n- Logical Thinking: 6 Questions\n- Arithmetic / Algebra: 6 Questions\n- Number Theory: 6 Questions\n- Geometry: 6 Questions\n- Combinatorics: 6 Questions\n\nTotal Score: 180 marks",
        "awards": "Score 144 and above: Gold Medal\nScore 108 - <144: Silver Medal\nScore 72 - <108: Bronze Medal\nScore 36 - <72: Merit Certificate",
        "finalRoundInfo": "",
        "compFee": "Free",
        "website": "http://www.worldimo.org/",
        "samplePaper": ""
    },
    {
        "id": "20",
        "name": "MWB (Mathematics Without Borders)",
        "location": "Bulgaria",
        "method": "Online",
        "language": "English",
        "showRegister": "Yes",
        "grades": "Grade 2 - Grade 10",
        "date": "27 October 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Age Group 1: Students born in 2017\nAge Group 2: Students born in 2016\nAge Group 3: Students born in 2015\nAge Group 4: Students born in 2014\nAge Group 5: Students born in 2013\nAge Group 6: Students born in 2012\nAge Group 7: Students born in 2011\nAge Group 8: Students born in 2010\nAge Group 9: Students born in 2009",
        "organizedBy": "Pedagogical Association Education Without Borders",
        "indonesiaLocalOrganizer": "Omnium Education",
        "structure": "20 Short Answer in 60 minutes",
        "awards": "For each Age Group, awards will be given based on global rank:\n\nTop 5%: Gold Medal\nNext 10%: Silver Medal\nNext 15%: Bronze Medal",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round in June in Bulgaria",
        "compFee": "IDR 300,000",
        "website": "https://mathwithoutborders.bg/public_html/en/",
        "samplePaper": "https://mathwithoutborders.bg/public_html/en/index.php/problems/"
    },
    {
        "id": "21",
        "name": "AMO (Asia Mathematics Olympics)",
        "location": "Japan",
        "method": "Online",
        "language": "English",
        "showRegister": "No",
        "grades": "Grade 1 - Grade 8",
        "date": "7 September 2024",
        "curated": "No",
        "prerequisites": "None",
        "category": "KidBee: Grade 1-3\nKidBee-Open: Grade 4-5\nSenior: Grade 6\nSenior-Open: Grade 7-8",
        "organizedBy": "Gakken Asia and Ministry of Japan Education, Sports, Culture, and Technology (MEXT)",
        "indonesiaLocalOrganizer": "",
        "structure": "KidBee: 8-10 Short Answer (60 minutes)\nKidBee-Open: 8-10 Short Answer (60 minutes)\nSenior: 10-12 Short Answer (90 minutes) \nSenior-Open: 10-12 Short Answer (90 minutes)\n\nSame questions for KidBee & KidBee-Open / Senior & Senior-Open, but grading will be differentiated based on category",
        "awards": "Awards (Gold / Silver / Bronze) will be given per category based on global rank",
        "finalRoundInfo": "Top 30% of the winners is eligible for the Final Round on 22-25 Nov 2025 in Shinjuku-Perfecture, Japan",
        "compFee": "",
        "website": "",
        "samplePaper": ""
    },
    {
        "id": "22",
        "name": "AMC 8 (American Mathematics Competition)",
        "location": "USA",
        "method": "Online",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Grade 3 - Grade 8",
        "date": "19 January 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Open Category (Same paper for all)",
        "organizedBy": "Mathematical Association of America",
        "indonesiaLocalOrganizer": "",
        "structure": "25 Multiple Choice in 40 minutes",
        "awards": "Perfect Score: 25 marks out of 25\nHonor Roll with Distinction: Min 21 marks out of 25 / Top 1% of all winners\nHonor Roll: Min 17 marks out of 25 / Top 5% of all winners\nAchievement Roll: Awarded to students in Grade 6 and below with a min score of 15 / Top 30% of winners from Grade 6 and below\n",
        "finalRoundInfo": "",
        "compFee": "",
        "website": "",
        "samplePaper": "https://artofproblemsolving.com/wiki/index.php/AMC_8_Problems_and_Solutions"
    },
    {
        "id": "23",
        "name": "AMC 10A (American Mathematics Competition)",
        "location": "USA",
        "method": "Online",
        "language": "English & Bahasa Indonesia",
        "showRegister": "Yes",
        "grades": "Grade 6 - Grade 10",
        "date": "7 November 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Open Category (Same paper for all)",
        "organizedBy": "Mathematical Association of America",
        "indonesiaLocalOrganizer": "",
        "structure": "25 Multiple Choice in 75 minutes",
        "awards": "",
        "finalRoundInfo": "",
        "compFee": "IDR 325,000 (until 23 Oct 2024)",
        "website": "",
        "samplePaper": "https://artofproblemsolving.com/wiki/index.php/AMC_10_Problems_and_Solutions"
    },
    {
        "id": "24",
        "name": "AMC 12A (American Mathematics Competition)",
        "location": "USA",
        "method": "Online",
        "language": "English & Bahasa Indonesia",
        "showRegister": "Yes",
        "grades": "Grade 9 - Grade 12",
        "date": "7 November 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Open Category (Same paper for all)",
        "organizedBy": "Mathematical Association of America",
        "indonesiaLocalOrganizer": "",
        "structure": "25 Multiple Choice in 75 minutes",
        "awards": "",
        "finalRoundInfo": "",
        "compFee": "IDR 325,000 (until 23 Oct 2024)",
        "website": "",
        "samplePaper": "https://artofproblemsolving.com/wiki/index.php/AMC_12_Problems_and_Solutions"
    },
    {
        "id": "25",
        "name": "AMC 10B (American Mathematics Competition)",
        "location": "USA",
        "method": "Online",
        "language": "English",
        "showRegister": "Yes",
        "grades": "Grade 6 - Grade 10",
        "date": "13 November 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Open Category (Same paper for all)",
        "organizedBy": "Mathematical Association of America",
        "indonesiaLocalOrganizer": "",
        "structure": "25 Multiple Choice in 75 minutes",
        "awards": "",
        "finalRoundInfo": "",
        "compFee": "IDR 325,000 (until 23 Oct 2024)",
        "website": "",
        "samplePaper": "https://artofproblemsolving.com/wiki/index.php/AMC_10_Problems_and_Solutions"
    },
    {
        "id": "26",
        "name": "AMC 12B (American Mathematics Competition)",
        "location": "USA",
        "method": "Online",
        "language": "English",
        "showRegister": "Yes",
        "grades": "Grade 9 - Grade 12",
        "date": "13 November 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Open Category (Same paper for all)",
        "organizedBy": "Mathematical Association of America",
        "indonesiaLocalOrganizer": "",
        "structure": "25 Multiple Choice in 75 minutes",
        "awards": "",
        "finalRoundInfo": "",
        "compFee": "IDR 325,000 (until 23 Oct 2024)",
        "website": "",
        "samplePaper": "https://artofproblemsolving.com/wiki/index.php/AMC_12_Problems_and_Solutions"
    },
    {
        "id": "27",
        "name": "IKMC (International Kangaroo Mathematics Contest)",
        "location": "France",
        "method": "Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "No",
        "grades": "Grade 1 - Grade 12",
        "date": "25 March 2024",
        "curated": "",
        "prerequisites": "None",
        "category": "Pre-Ecolier: Grade 1-2\nEcolier: Grade 3-4\nBenjamin: Grade 5-6\nCadet: Grade 7-8\nJunior: Grade 9-10\nSenior: Grade 11-12",
        "organizedBy": "Association Kangourou sans Frontieres",
        "indonesiaLocalOrganizer": "KPM",
        "structure": "Pre-Ecolier & Ecolier:  24 Multiple Choice in 75 minutes\n- 8 Easy problems (3 marks each)\n- 8 Medium problems (4 marks each)\n- 8 Hard problems (5 marks each)\nTotal Score: 96\n\nBenjamin, Cadet, Junior, and Senior: 30 Multiple Choice in 90 minutes\n- 10 Easy problems (3 marks each)\n- 10 Medium problems (4 marks each)\n- 10 Hard problems (5 marks each)\nTotal Score: 120\n",
        "awards": "Awards will be differentiated by grade level: Gold / Silver / Bronze",
        "finalRoundInfo": "",
        "compFee": "",
        "website": "",
        "samplePaper": ""
    },
    {
        "id": "28",
        "name": "JISMO (Japan International Science & Mathematics Olympiad)",
        "location": "Japan",
        "method": "Online & Offline",
        "language": "English & Bahasa Indonesia",
        "showRegister": "Yes",
        "grades": "Grade 2 - Grade 6",
        "date": "28 Sep 2024\n5, 12, 19, 26 Oct 2024 \n2 Nov 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "G2, G3, G4, G5, G6",
        "organizedBy": "JISMO Organizing Committee",
        "indonesiaLocalOrganizer": "Yayasan Mirai Indonesia",
        "structure": "22 Multiple Choice n 60 minutes",
        "awards": "Top 1%: Diamond Medal\nNext 10%: Ruby Medal\nNext 10%: Emerald Medal\nNext 10%: Sapphire Medal\nNext 15%: Good Effort",
        "finalRoundInfo": "",
        "compFee": "IDR 320,000",
        "website": "",
        "samplePaper": ""
    },
    {
        "id": "29",
        "name": "FISO (Future Intelligence Students Olympiad)",
        "location": "USA",
        "method": "Online",
        "language": "English & Bahasa Indonesia",
        "showRegister": "Yes",
        "grades": "Kindergarten - Grade 12",
        "date": "8-9 Dec 2024",
        "curated": "Yes",
        "prerequisites": "None",
        "category": "Category 1: Kindergarten\nCategory 2: G1-G2\nCategory 3: G3-G4\nCategory 4: G5-G6\nCategory 5: G7-G8\nCategory 6: G9-G10\nCategory 7: G11-G12",
        "organizedBy": "",
        "indonesiaLocalOrganizer": "IMASO",
        "structure": "25 Questions in 60 minutes:\n20 Multiple Choice\n5 Short Answer",
        "awards": "Top 5%: Gold Medal\nNext 10%: Silver Medal\nNext 20%: Bronze Medal",
        "finalRoundInfo": "Gold, Silver, and Bronze is eligible for the Final Round. Gold Medal can participate for free",
        "compFee": "IDR 275,000",
        "website": "",
        "samplePaper": ""
    }
]
